package streamingapi

import "github.com/mytn1992/ebd-carpark-streaming-api/pkg/cmd/random_elastic"

// Generated by https://quicktype.io

type OnemapResponse struct {
	Found         int64    `json:"found"`
	TotalNumPages int64    `json:"totalNumPages"`
	PageNum       int64    `json:"pageNum"`
	Results       []Result `json:"results"`
}

type Result struct {
	Searchval  string `json:"SEARCHVAL"`
	BlkNo      string `json:"BLK_NO"`
	RoadName   string `json:"ROAD_NAME"`
	Building   string `json:"BUILDING"`
	Address    string `json:"ADDRESS"`
	Postal     string `json:"POSTAL"`
	X          string `json:"X"`
	Y          string `json:"Y"`
	Latitude   string `json:"LATITUDE"`
	Longitude  string `json:"LONGITUDE"`
	Longtitude string `json:"LONGTITUDE"`
}

type Buildings struct {
	Address    string `json:"ADDRESS"`
	BlkNo      string `json:"BLK_NO"`
	Building   string `json:"BUILDING"`
	Latitude   string `json:"LATITUDE"`
	Longitude  string `json:"LONGITUDE"`
	Longtitude string `json:"LONGTITUDE"`
	Postal     string `json:"POSTAL"`
	RoadName   string `json:"ROAD_NAME"`
	Searchval  string `json:"SEARCHVAL"`
	X          string `json:"X"`
	Y          string `json:"Y"`
}

type KafkaPayload struct {
	Records []Payload `json:"records"`
}
type Payload struct {
	Key   string          `json:"key"`
	Value KafkaStreamBody `json:"value"`
}

type KafkaStreamBody struct {
	Userinput  random_elastic.Buildings `json:"user_input"`
	ResultList []PredictionResult       `json:"result_list"`
}

type PredictionResult struct {
	PredictionPointList    []PredictionPoint `json:"prediction_point_list"`
	Car_park_no            string            `json:"car_park_no"`
	Address                string            `json:"address"`
	Latitude               string            `json:"latitude"`
	Longitude              string            `json:"longitude"`
	Location               interface{}       `json:"location"`
	Distance               string            `json:"distance"`
	Current_Lots_Available string            `json:"current_lots_available"`
	Time                   string            `json:"time"`
}

type PredictionPoint struct {
	Time  string `json:"time"`
	Value string `json:"value"`
}
