service: ebd-carpark-streaming-api # NOTE: update this with your service name
frameworkVersion: '2'

provider:
  name: aws
  region: ap-southeast-1
  runtime: go1.x
  stage: ${opt:stage, 'dev'}
  lambdaHashingVersion: 20201221 
  environment:
    ENV: ${self:provider.stage}

package:
  individually: true
  patterns:
    - '!./**'

functions:
  ebd-carpark-user-query:
    package:
      patterns:
        - bin/post
    handler: bin/post
    description: ebd carpark availabilty user query
    timeout: 30
    memorySize: 256
    events:
      - http:
          path: event
          method: post
          cors: true 


